server.port=8081

application-title=Auth Service

spring.application.name=auth-service

spring.config.import=configserver:http://config-server:8888/
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/