apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/postgres
  - base/zookeeper
  - base/kafka
  - base/kafka-ui
  - base/gateway
  - base/config-server
  - base/eureka-server
  - base/frontend
  - base/user-service
  - base/auth-service
  - base/role-service