server.port=8082

spring.application.name=role-service

application-title=Role Service

spring.config.import=configserver:http://config-server:8888/
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/